inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-shopify: rubocop.yml

Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/dummy/db/schema.rb'
    - 'db/migrate/*'

Style/MethodCallWithArgsParentheses:
  Exclude:
    - 'spec/dummy/db/schema.rb'

